name = "Alba gu bràth"
author = "Lutitious"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7eef046e773d8676667c613c0bcde2e58c311f49ef09f4463c514a93a7da72d7"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
