name = "Tadger"
author = "Lutitious"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06e8a9426f06f3407389c35a659fdd446837406d04a08650938667dccd5318ce"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
