name = "Alba gu bràth"
author = "Lutitious"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea505c2af7744a919df64b7ec0429e42a5b4a56dfd111e9493c828500014dab4"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
